platform :android do
  desc "Building your App in version beta"
  lane :fire_dev do |options|
    ENV["ENVFILE"]=".env.#{ENV["BUILD_TYPE"]}"
    puts "+---------------------------------+".bold.blue
    puts "|-- Environment: #{options[:env]} 🚀 --|".bold.blue
    puts "+---------------------------------+".bold.blue

    # increment_version_code(
    #   gradle_file_path: "android/app/build.gradle",
    # )
    gradle(
      project_dir: './android',
      task: "clean assemble",
      flavor: ENV["FLAVOR"],
      build_type: "Release"
    )
    firebase_app_distribution(
      app: ENV['ANDROID_APP_ID'],
      groups: ENV["GROUPS"] || options[:groups],
      release_notes: options[:notes] || "My App Auto Build",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end

platform :ios do
  desc "Building your App in beta version"
  lane :fire_dev do |options|
    ENV["ENVFILE"]=".env.#{ENV["BUILD_TYPE"]}"
    build(profile: options[:env])
    firebase_app_distribution(
      app: ENV['IOS_APP_ID'],
      groups: ENV["GROUPS"] || options[:groups],
      release_notes: options[:notes] || "My App Auto Build",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end

  private_lane :build do |options|
    puts "+------------------------------------+".bold.blue
    puts "|-- Environment: #{options[:profile]} 🚀 --|".bold.blue
    puts "+------------------------------------+".bold.blue

    import_certificate(
      keychain_name: "login",
      certificate_path: "certificates/Certificates.p12",
      certificate_password: "1",
      keychain_password: ""
    )

    profile_path = "./certificates/#{ENV["DISTRIBUTION_PROFILE_NAME"]}.mobileprovision"
    install_provisioning_profile(path: profile_path)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./ios/MyApp.xcodeproj"
    )
    update_project_provisioning(
      xcodeproj: "./ios/MyApp.xcodeproj",
      profile: profile_path,
      target_filter: "MyApp",
      build_configuration: ENV['CONFIGURATION_NAME']
    )

    # increment_build_number(
    #     xcodeproj: './ios/MyApp.xcodeproj'
    # )

    scheme = ENV['SCHEME_NAME']
    method = "enterprise"
    profile = ENV['DISTRIBUTION_PROFILE_FIREBASE']
    build_app(
      workspace: "./ios/MtApp.xcworkspace",
      scheme: scheme,
      configuration: ENV['CONFIGURATION_NAME'],
      export_options: {
        method: method,
        provisioningProfiles: {
          ENV['BUNDLE_ID'] => profile
        }
      },
      include_bitcode: true,
      clean: true
    )
  end
end
